// Production demand generated by released sales orders. Read + status updates.
import { supabase } from '../lib/supabaseClient';

export async function listDemand() {
  const { data, error } = await supabase.from('production_demand').select('*').order('required_date', { ascending: true });
  if (error) throw error;
  return data || [];
}

export async function updateDemand(id, patch) {
  const { error } = await supabase.from('production_demand').update({ ...patch, updated_at: new Date().toISOString() }).eq('id', id);
  if (error) throw error;
}

const DEMAND_FLOW = { pending: 'planned', planned: 'in_production', in_production: 'done' };
export const nextDemandStatus = (s) => DEMAND_FLOW[s] || null;

const productionDemandService = { listDemand, updateDemand, nextDemandStatus };
export default productionDemandService;
